basePath: /v1/appointment
definitions:
  model.AppResponse:
    properties:
      appointment_date:
        example: "2022-06-23T21:12:02.000000001Z"
        type: string
      id:
        example: 62b65300e1d7eab1ea9a681d
        type: string
      salon_id:
        example: 1
        type: integer
      user_id:
        example: 1
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: leandro1997silva97@gmail.com
    name: API Support
    url: https://github.com/LeandroAlcantara-1997
  description: This is a service for make appointments .
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Appointment API
  version: "1.0"
paths:
  /appointment:
    get:
      consumes:
      - application/json
      description: get all appointments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.AppResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
        "404":
          description: Not Found
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: Get all appointments
      tags:
      - appointment
  /appointment/{id}:
    delete:
      consumes:
      - application/json
      description: get string by ID and delete an appointment
      parameters:
      - description: Appointment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "404":
          description: Not Found
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: Delete appointments by id
      tags:
      - appointment
    put:
      consumes:
      - application/json
      description: get string by ID and body for update
      parameters:
      - description: Appointment ID
        in: path
        name: id
        required: true
        type: string
      - description: body appointment
        in: body
        name: appointment
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AppResponse'
        "400":
          description: Bad Request
          schema:
            type: ""
        "404":
          description: Not Found
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: Update an appointment
      tags:
      - appointment
  /appointment/available:
    get:
      consumes:
      - application/json
      description: get all available appointments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.AppResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
        "404":
          description: Not Found
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: Get available appointments
      tags:
      - appointment
  /appointment/salon/{id}:
    get:
      consumes:
      - application/json
      description: get string by salon ID and return an appointment
      parameters:
      - description: Salon ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.AppResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
        "404":
          description: Not Found
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: Get appointments by user ids
      tags:
      - appointment
  /appointment/user/{id}:
    get:
      consumes:
      - application/json
      description: get string by user ID and return an appointment
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.AppResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
        "404":
          description: Not Found
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: Get appointments by user ids
      tags:
      - appointment
swagger: "2.0"
